// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#ifndef UI_EASTER_EGG_H
#define UI_EASTER_EGG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_EASTER_EGG
extern void ui_EASTER_EGG_screen_init(void);
extern void ui_EASTER_EGG_screen_destroy(void);
extern lv_obj_t * ui_EASTER_EGG;
extern void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Label8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

