// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#include "ui.h"

lv_obj_t * ui_EASTER_EGG = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Label8 = NULL;
// event funtions
void ui_event_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Schermata_Diagnostica, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Schermata_Diagnostica_screen_init);
    }
}

// build funtions

void ui_EASTER_EGG_screen_init(void)
{
    ui_EASTER_EGG = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_EASTER_EGG, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_EASTER_EGG, &ui_img_foto_sfondo_resized_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button4 = lv_button_create(ui_EASTER_EGG);
    lv_obj_set_width(ui_Button4, 100);
    lv_obj_set_height(ui_Button4, 31);
    lv_obj_set_x(ui_Button4, 159);
    lv_obj_set_y(ui_Button4, 121);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "RITORNA");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button4, ui_event_Button4, LV_EVENT_ALL, NULL);

}

void ui_EASTER_EGG_screen_destroy(void)
{
    if(ui_EASTER_EGG) lv_obj_del(ui_EASTER_EGG);

    // NULL screen variables
    ui_EASTER_EGG = NULL;
    ui_Button4 = NULL;
    ui_Label8 = NULL;

}
