// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#ifndef UI_JOGGER_H
#define UI_JOGGER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_JOGGER
extern void ui_JOGGER_screen_init(void);
extern void ui_JOGGER_screen_destroy(void);
extern lv_obj_t * ui_JOGGER;
extern void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_BotContrMotPunz;
extern lv_obj_t * ui_ContrMotPunz;
extern lv_obj_t * ui_BotControMotTamb;
extern lv_obj_t * ui_ContrMotTamb;
extern lv_obj_t * ui_ContrPunz;
extern lv_obj_t * ui_ContrPunz1;
extern lv_obj_t * ui_CLOSE;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_PulsPunz;
extern lv_obj_t * ui_PulsONPunz;
extern lv_obj_t * ui_ONPunz;
extern lv_obj_t * ui_PulsJogIndPunz;
extern lv_obj_t * ui_IndPunz;
extern lv_obj_t * ui_PulsJogAvPunz;
extern lv_obj_t * ui_AvPunz;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_JOGGER;
extern lv_obj_t * uic_BotContrMotPunz;
extern lv_obj_t * uic_BotControMotTamb;
extern lv_obj_t * uic_ContrMotTamb;
extern lv_obj_t * uic_ContrPunz;
extern lv_obj_t * uic_CLOSE;
extern lv_obj_t * uic_PulsONPunz;
extern lv_obj_t * uic_ONPunz;
extern lv_obj_t * uic_PulsJogIndPunz;
extern lv_obj_t * uic_IndPunz;
extern lv_obj_t * uic_PulsJogAvPunz;
extern lv_obj_t * uic_AvPunz;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

