// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#include "ui.h"

lv_obj_t * uic_AvPunz;
lv_obj_t * uic_PulsJogAvPunz;
lv_obj_t * uic_IndPunz;
lv_obj_t * uic_PulsJogIndPunz;
lv_obj_t * uic_ONPunz;
lv_obj_t * uic_PulsONPunz;
lv_obj_t * uic_CLOSE;
lv_obj_t * uic_ContrPunz;
lv_obj_t * uic_ContrMotTamb;
lv_obj_t * uic_BotControMotTamb;
lv_obj_t * uic_BotContrMotPunz;
lv_obj_t * uic_JOGGER;
lv_obj_t * ui_JOGGER = NULL;
lv_obj_t * ui_Button3 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_BotContrMotPunz = NULL;
lv_obj_t * ui_ContrMotPunz = NULL;
lv_obj_t * ui_BotControMotTamb = NULL;
lv_obj_t * ui_ContrMotTamb = NULL;
lv_obj_t * ui_ContrPunz = NULL;
lv_obj_t * ui_ContrPunz1 = NULL;
lv_obj_t * ui_CLOSE = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_PulsPunz = NULL;
lv_obj_t * ui_PulsONPunz = NULL;
lv_obj_t * ui_ONPunz = NULL;
lv_obj_t * ui_PulsJogIndPunz = NULL;
lv_obj_t * ui_IndPunz = NULL;
lv_obj_t * ui_PulsJogAvPunz = NULL;
lv_obj_t * ui_AvPunz = NULL;
lv_obj_t * ui_Panel3 = NULL;
lv_obj_t * ui_Panel4 = NULL;
// event funtions
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Schermata_Diagnostica, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Schermata_Diagnostica_screen_init);
    }
}

// build funtions

void ui_JOGGER_screen_init(void)
{
    ui_JOGGER = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_JOGGER, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_JOGGER, &ui_img_foto_sfondo_resized_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_button_create(ui_JOGGER);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 31);
    lv_obj_set_x(ui_Button3, 159);
    lv_obj_set_y(ui_Button3, 121);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "RITORNA");
    lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BotContrMotPunz = lv_button_create(ui_JOGGER);
    lv_obj_set_width(ui_BotContrMotPunz, 200);
    lv_obj_set_height(ui_BotContrMotPunz, 120);
    lv_obj_set_x(ui_BotContrMotPunz, -110);
    lv_obj_set_y(ui_BotContrMotPunz, 0);
    lv_obj_set_align(ui_BotContrMotPunz, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BotContrMotPunz, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BotContrMotPunz, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContrMotPunz = lv_label_create(ui_BotContrMotPunz);
    lv_obj_set_width(ui_ContrMotPunz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ContrMotPunz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ContrMotPunz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ContrMotPunz, "MOVIMENTAZIONE \nMOTORE\nPUNZONE");
    lv_obj_set_style_text_align(ui_ContrMotPunz, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BotControMotTamb = lv_button_create(ui_JOGGER);
    lv_obj_set_width(ui_BotControMotTamb, 200);
    lv_obj_set_height(ui_BotControMotTamb, 120);
    lv_obj_set_x(ui_BotControMotTamb, 115);
    lv_obj_set_y(ui_BotControMotTamb, 0);
    lv_obj_set_align(ui_BotControMotTamb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BotControMotTamb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BotControMotTamb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContrMotTamb = lv_label_create(ui_BotControMotTamb);
    lv_obj_set_width(ui_ContrMotTamb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ContrMotTamb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ContrMotTamb, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ContrMotTamb, "MOVIMENTAZIONE\nMOTORE\nTAMBURO");
    lv_obj_set_style_text_align(ui_ContrMotTamb, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContrPunz = lv_obj_create(ui_JOGGER);
    lv_obj_set_width(ui_ContrPunz, 440);
    lv_obj_set_height(ui_ContrPunz, 250);
    lv_obj_set_align(ui_ContrPunz, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ContrPunz, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContrPunz1 = lv_label_create(ui_ContrPunz);
    lv_obj_set_width(ui_ContrPunz1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ContrPunz1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ContrPunz1, 0);
    lv_obj_set_y(ui_ContrPunz1, -100);
    lv_obj_set_align(ui_ContrPunz1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ContrPunz1, "Controllo motore Punzone");

    ui_CLOSE = lv_obj_create(ui_ContrPunz);
    lv_obj_set_width(ui_CLOSE, 100);
    lv_obj_set_height(ui_CLOSE, 31);
    lv_obj_set_x(ui_CLOSE, -2);
    lv_obj_set_y(ui_CLOSE, 100);
    lv_obj_set_align(ui_CLOSE, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CLOSE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_CLOSE);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "X   CHIUDI");

    ui_PulsPunz = lv_obj_create(ui_ContrPunz);
    lv_obj_remove_style_all(ui_PulsPunz);
    lv_obj_set_width(ui_PulsPunz, 345);
    lv_obj_set_height(ui_PulsPunz, 66);
    lv_obj_set_x(ui_PulsPunz, 0);
    lv_obj_set_y(ui_PulsPunz, -50);
    lv_obj_set_align(ui_PulsPunz, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_PulsPunz, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PulsONPunz = lv_button_create(ui_PulsPunz);
    lv_obj_set_width(ui_PulsONPunz, 116);
    lv_obj_set_height(ui_PulsONPunz, 50);
    lv_obj_set_align(ui_PulsONPunz, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PulsONPunz, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_PulsONPunz, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PulsONPunz, lv_color_hex(0x01C413), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PulsONPunz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ONPunz = lv_label_create(ui_PulsONPunz);
    lv_obj_set_width(ui_ONPunz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ONPunz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ONPunz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ONPunz, "ABILITATO");

    ui_PulsJogIndPunz = lv_button_create(ui_PulsPunz);
    lv_obj_set_width(ui_PulsJogIndPunz, 100);
    lv_obj_set_height(ui_PulsJogIndPunz, 50);
    lv_obj_set_x(ui_PulsJogIndPunz, -115);
    lv_obj_set_y(ui_PulsJogIndPunz, 0);
    lv_obj_set_align(ui_PulsJogIndPunz, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PulsJogIndPunz, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_PulsJogIndPunz, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IndPunz = lv_label_create(ui_PulsJogIndPunz);
    lv_obj_set_width(ui_IndPunz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IndPunz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_IndPunz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IndPunz, "jog-");

    ui_PulsJogAvPunz = lv_button_create(ui_PulsPunz);
    lv_obj_set_width(ui_PulsJogAvPunz, 100);
    lv_obj_set_height(ui_PulsJogAvPunz, 50);
    lv_obj_set_x(ui_PulsJogAvPunz, 115);
    lv_obj_set_y(ui_PulsJogAvPunz, 0);
    lv_obj_set_align(ui_PulsJogAvPunz, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PulsJogAvPunz, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_PulsJogAvPunz, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AvPunz = lv_label_create(ui_PulsJogAvPunz);
    lv_obj_set_width(ui_AvPunz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AvPunz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AvPunz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AvPunz, "Jog+");

    ui_Panel3 = lv_obj_create(ui_JOGGER);
    lv_obj_set_width(ui_Panel3, 50);
    lv_obj_set_height(ui_Panel3, 50);
    lv_obj_set_x(ui_Panel3, -143);
    lv_obj_set_y(ui_Panel3, 22);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel4 = lv_obj_create(ui_JOGGER);
    lv_obj_set_width(ui_Panel4, 100);
    lv_obj_set_height(ui_Panel4, 50);
    lv_obj_set_x(ui_Panel4, -133);
    lv_obj_set_y(ui_Panel4, 84);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);
    uic_JOGGER = ui_JOGGER;
    uic_BotContrMotPunz = ui_BotContrMotPunz;
    uic_BotControMotTamb = ui_BotControMotTamb;
    uic_ContrMotTamb = ui_ContrMotTamb;
    uic_ContrPunz = ui_ContrPunz;
    uic_CLOSE = ui_CLOSE;
    uic_PulsONPunz = ui_PulsONPunz;
    uic_ONPunz = ui_ONPunz;
    uic_PulsJogIndPunz = ui_PulsJogIndPunz;
    uic_IndPunz = ui_IndPunz;
    uic_PulsJogAvPunz = ui_PulsJogAvPunz;
    uic_AvPunz = ui_AvPunz;

}

void ui_JOGGER_screen_destroy(void)
{
    if(ui_JOGGER) lv_obj_del(ui_JOGGER);

    // NULL screen variables
    uic_JOGGER = NULL;
    ui_JOGGER = NULL;
    ui_Button3 = NULL;
    ui_Label7 = NULL;
    uic_BotContrMotPunz = NULL;
    ui_BotContrMotPunz = NULL;
    ui_ContrMotPunz = NULL;
    uic_BotControMotTamb = NULL;
    ui_BotControMotTamb = NULL;
    uic_ContrMotTamb = NULL;
    ui_ContrMotTamb = NULL;
    uic_ContrPunz = NULL;
    ui_ContrPunz = NULL;
    ui_ContrPunz1 = NULL;
    uic_CLOSE = NULL;
    ui_CLOSE = NULL;
    ui_Label9 = NULL;
    ui_PulsPunz = NULL;
    uic_PulsONPunz = NULL;
    ui_PulsONPunz = NULL;
    uic_ONPunz = NULL;
    ui_ONPunz = NULL;
    uic_PulsJogIndPunz = NULL;
    ui_PulsJogIndPunz = NULL;
    uic_IndPunz = NULL;
    ui_IndPunz = NULL;
    uic_PulsJogAvPunz = NULL;
    ui_PulsJogAvPunz = NULL;
    uic_AvPunz = NULL;
    ui_AvPunz = NULL;
    ui_Panel3 = NULL;
    ui_Panel4 = NULL;

}
