// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#ifndef UI_SCHERAMATA_AVVIO_H
#define UI_SCHERAMATA_AVVIO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Scheramata_Avvio
extern void ui_Scheramata_Avvio_screen_init(void);
extern void ui_Scheramata_Avvio_screen_destroy(void);
extern void ui_event_Scheramata_Avvio(lv_event_t * e);
extern lv_obj_t * ui_Scheramata_Avvio;
extern lv_obj_t * ui_CARICAMENTO_INIZIO;
extern lv_obj_t * ui_INIZIO;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label5;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Schermata_Iniziale;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

