clear;
clc;
close all;
%% ===============================
% PARAMETRI MOTORE
%% ===============================
T_hold = 0.48;        % Coppia di tenuta [N·m]
omega_c_24V = 90;     % dinamica 24V
omega_c_12V = 40;     % dinamica 12V
%% ===============================
% VELOCITA' (rad/s -> °/s)
%% ===============================
omega = linspace(0,130,700);
deg_s = omega * 180/pi;
%% ===============================
% MODELLO COPPIA
%% ===============================
T_24V = T_hold ./ sqrt(1 + (omega./omega_c_24V).^2);
T_12V = T_hold ./ sqrt(1 + (omega./omega_c_12V).^2);
%% ===============================
% FIGURA
%% ===============================
figure('Color',[0.93 0.93 0.93],...
       'Position',[100 100 1200 650]);
ax = axes('Position',[0.08 0.15 0.75 0.75]);
hold on
box on
set(gca,...
    'Color','white',...
    'FontSize',12,...
    'FontWeight','bold',...
    'LineWidth',1.3,...
    'XColor','k',...  % FORZA I NUMERI ASSE X IN NERO
    'YColor','k')     % FORZA I NUMERI ASSE Y IN NERO
%% ===============================
% GRIGLIA DATASHEET
%% ===============================
grid on
ax.GridAlpha = 0.35;
ax.MinorGridAlpha = 0.15;
ax.XMinorGrid='on';
ax.YMinorGrid='on';
%% ===============================
% CURVE
%% ===============================
% Aggiunti i marker '.' con una dimensione di 15. 
% MarkerIndices disegna un pallino ogni 20 punti per evitare sovrapposizioni.
plot(deg_s,T_24V,'b','LineWidth',3, 'Marker', '.', 'MarkerSize', 15, 'MarkerIndices', 1:20:length(deg_s))
plot(deg_s,T_12V,'r--','LineWidth',3, 'Marker', '.', 'MarkerSize', 15, 'MarkerIndices', 1:20:length(deg_s))
yline(T_hold,'k:','LineWidth',2.5)
%% ===============================
% ASSI
%% ===============================
xlabel('VELOCITÀ DI ROTAZIONE [°/s]','FontSize',13,'FontWeight','bold','Color','k')
ylabel('COPPIA [N·m]','FontSize',13,'FontWeight','bold','Color','k')
title({'CURVA DI COPPIA REALE','Stepper NEMA17 42BYGHW811'},...
      'FontSize',18,'FontWeight','bold','Color','k')
xlim([0 max(deg_s)])
ylim([0 0.6])
%% ===============================
% ENFASI VALORE 0.48 (Mantenendo lo 0.5)
%% ===============================
% Testo rosso e in grassetto stampato fuori dal grafico
text(0, T_hold, '0.48 ', ...
    'Color', 'r', ...
    'FontSize', 13, ...
    'FontWeight', 'bold', ...
    'HorizontalAlignment', 'right', ...
    'VerticalAlignment', 'middle')
% Pallino rosso di ancoraggio sull'asse
plot(0, T_hold, 'ro', 'MarkerSize', 5, 'MarkerFaceColor', 'r', 'Clipping', 'off');
%% ===============================
% REGIONI OPERATIVE
%% ===============================
% Funzionamento continuo
patch([0 4500 4500 0],...
      [0 0 T_hold T_hold],...
      [0.85 0.92 1],...
      'FaceAlpha',0.5,...
      'EdgeColor','none')
text(1200,0.07,...
'REGIONE DI FUNZIONAMENTO CONTINUO',...
'FontSize',12,'FontWeight','bold','Color','k') % TESTO NERO
% Rischio stallo
patch([5000 max(deg_s) max(deg_s) 5000],...
      [0 0 T_hold T_hold],...
      [1 0.85 0.85],...
      'FaceAlpha',0.5,...
      'EdgeColor','none')
text(5200,0.43,...
'REGIONE DI RISCHIO DI STALLO',...
'FontSize',12,'FontWeight','bold','Color','k') % TESTO NERO
%% ===============================
% BOX DATI TECNICI
%% ===============================
annotation('textbox',[0.85 0.55 0.13 0.25],...
'String',sprintf(['DATI TECNICI\n',...
'Corrente: 2.5 A/fase\n',...
'Induttanza: 1.8 mH\n',...
'Holding Torque:\n0.48 N·m']),...
'BackgroundColor','white',...
'EdgeColor','black',...
'Color','k',... % TESTO NERO PER L'ANNOTATION
'FontSize',11,...
'FontWeight','bold')
%% ===============================
% LEGENDA
%% ===============================
legend({'24V Alimentazione',...
        '12V Alimentazione',...
        'Holding Torque'},...
        'Location','northeast',...
        'FontSize',11,...
        'TextColor','k',...
        'Color','w',...
        'EdgeColor','k')