/** 
 * This file was generated by SquareLine Studio
 * SquareLine Studio version: SquareLine Studio 1.6.0
 * LVGL version: 9.3
 * Project name: HMI_Decapsulator
 * @link Documentazione Squareline: https://docs.squareline.io/docs/
 * @brief Questo file gestisce delle callback associate agli eventi dell'HMI.
 * @attention 	- Evitare operazioni bloccanti all'interno delle callback.
 *				- Seguire la documentazione Doxygen Standard
 *				  @link https://www.doxygen.nl/manual/docblocks.html
 * @author Alessio Pisan
 */

#include "ui.h"
#include "JogMotoriPRG.hpp"
#include "DecapsulatorPRG.hpp"

/**
 * @example Così andranno fatte praticamente tutte le funzioni degli eventi
 * 
 * @exception Quando farai gli eventi del Jog dovrai anche mandare JogStatus
 * 
 * @exception Quando farai gli eventi del pulsante che fa passare dalla schermata
 *			  Principale a quella di Jog dovrai fare anche :
 *			  @code
 *			  ... 
 *			  vTaskSuspend(MainPrgHandler);
 *			  vTaskResume(JogMotoriPrgHandler);
 *			  ... 
 *			  @endcode

 * @exception Quando farai gli eventi del pulsante che fa passare dalla schermata
 *			  di Jog a quella Principale dovrai fare anche :
 *			  @code
 *			  ... 
 *			  vTaskSuspend(JogMotoriPrgHandler);
 *			  vTaskResume(MainPrgHandler);
 *			  ... 
 *			  @endcode  
 */
void avvio_macchina(lv_event_t * e)
{
	CommandQueueHMI_t cmd = defaultCommandQueueHMI;

	cmd.obj  = lv_event_get_original_target(e);
	cmd.evt_type = lv_event_get_code(e);

	sendUpdateHMI(cmd, bool* sendChanges);
}

void Stop_Macchina(lv_event_t * e)
{
	
}
