// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#include "ui.h"

lv_obj_t * uic_Schermata_Iniziale;
lv_obj_t * ui_Scheramata_Avvio = NULL;
lv_obj_t * ui_Scheramata_Avvio_CARICAMENTO_INIZIO = NULL;
lv_obj_t * ui_Scheramata_Avvio_INIZIO = NULL;
lv_obj_t * ui_Scheramata_Avvio_Label3 = NULL;
lv_obj_t * ui_Scheramata_Avvio_Label5 = NULL;
// event funtions
void ui_event_Scheramata_Avvio(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Scheramata_Avvio_Label3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Scheramata_Avvio_INIZIO, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_screen_change(&ui_Schermata_Principale, LV_SCR_LOAD_ANIM_FADE_ON, 100, 0, &ui_Schermata_Principale_screen_init);
    }
}

// build funtions

void ui_Scheramata_Avvio_screen_init(void)
{
    ui_Scheramata_Avvio = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Scheramata_Avvio, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Scheramata_Avvio, lv_color_hex(0xD42222), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Scheramata_Avvio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Scheramata_Avvio, &ui_img_1415156368, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor(ui_Scheramata_Avvio, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_recolor_opa(ui_Scheramata_Avvio, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scheramata_Avvio_CARICAMENTO_INIZIO = lv_spinner_create(ui_Scheramata_Avvio);
    //lv_spinner_set_anim_params(ui_Scheramata_Avvio_CARICAMENTO_INIZIO, 1000, 90);
    lv_obj_set_width(ui_Scheramata_Avvio_CARICAMENTO_INIZIO, 177);
    lv_obj_set_height(ui_Scheramata_Avvio_CARICAMENTO_INIZIO, 41);
    lv_obj_set_x(ui_Scheramata_Avvio_CARICAMENTO_INIZIO, 11);
    lv_obj_set_y(ui_Scheramata_Avvio_CARICAMENTO_INIZIO, 130);
    lv_obj_set_align(ui_Scheramata_Avvio_CARICAMENTO_INIZIO, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Scheramata_Avvio_CARICAMENTO_INIZIO, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Scheramata_Avvio_INIZIO = lv_label_create(ui_Scheramata_Avvio_CARICAMENTO_INIZIO);
    lv_obj_set_width(ui_Scheramata_Avvio_INIZIO, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scheramata_Avvio_INIZIO, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Scheramata_Avvio_INIZIO, 10);
    lv_obj_set_y(ui_Scheramata_Avvio_INIZIO, 0);
    lv_obj_set_align(ui_Scheramata_Avvio_INIZIO, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Scheramata_Avvio_INIZIO, "Avvio in corso");
    lv_obj_set_style_text_color(ui_Scheramata_Avvio_INIZIO, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Scheramata_Avvio_INIZIO, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scheramata_Avvio_Label3 = lv_label_create(ui_Scheramata_Avvio_CARICAMENTO_INIZIO);
    lv_obj_set_width(ui_Scheramata_Avvio_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scheramata_Avvio_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Scheramata_Avvio_Label3, 24);
    lv_obj_set_y(ui_Scheramata_Avvio_Label3, 0);
    lv_obj_set_align(ui_Scheramata_Avvio_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Scheramata_Avvio_Label3, "Avvio Completato");
    lv_obj_add_flag(ui_Scheramata_Avvio_Label3, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Scheramata_Avvio_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Scheramata_Avvio_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Scheramata_Avvio_Label5 = lv_label_create(ui_Scheramata_Avvio);
    lv_obj_set_width(ui_Scheramata_Avvio_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Scheramata_Avvio_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Scheramata_Avvio_Label5, 1);
    lv_obj_set_y(ui_Scheramata_Avvio_Label5, -130);
    lv_obj_set_align(ui_Scheramata_Avvio_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Scheramata_Avvio_Label5, "GRUPPO MB N.1 \"DECAPSULATOR\"");
    ui_object_set_themeable_style_property(ui_Scheramata_Avvio_Label5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_white);
    ui_object_set_themeable_style_property(ui_Scheramata_Avvio_Label5, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_white);
    lv_obj_set_style_text_font(ui_Scheramata_Avvio_Label5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Scheramata_Avvio, ui_event_Scheramata_Avvio, LV_EVENT_ALL, NULL);
    uic_Schermata_Iniziale = ui_Scheramata_Avvio;

}

void ui_Scheramata_Avvio_screen_destroy(void)
{
    if(ui_Scheramata_Avvio) lv_obj_del(ui_Scheramata_Avvio);

    // NULL screen variables
    uic_Schermata_Iniziale = NULL;
    ui_Scheramata_Avvio = NULL;
    ui_Scheramata_Avvio_CARICAMENTO_INIZIO = NULL;
    ui_Scheramata_Avvio_INIZIO = NULL;
    ui_Scheramata_Avvio_Label3 = NULL;
    ui_Scheramata_Avvio_Label5 = NULL;

}
