// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#ifndef UI_LOGGER1_H
#define UI_LOGGER1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Logger1
extern void ui_Logger1_screen_init(void);
extern void ui_Logger1_screen_destroy(void);
extern lv_obj_t * ui_Logger1;
extern lv_obj_t * ui_Logger1_LOGGER2;
extern void ui_event_Logger1_Button2(lv_event_t * e);
extern lv_obj_t * ui_Logger1_Button2;
extern lv_obj_t * ui_Logger1_Label4;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

