// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#ifndef UI_SCHERMATA_DIAGNOSTICA_H
#define UI_SCHERMATA_DIAGNOSTICA_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Schermata_Diagnostica
extern void ui_Schermata_Diagnostica_screen_init(void);
extern void ui_Schermata_Diagnostica_screen_destroy(void);
extern lv_obj_t * ui_Schermata_Diagnostica;
extern void ui_event_Schermata_Diagnostica_Button6(lv_event_t * e);
extern lv_obj_t * ui_Schermata_Diagnostica_Button6;
extern lv_obj_t * ui_Schermata_Diagnostica_Label13;
extern lv_obj_t * ui_Schermata_Diagnostica_Button1;
extern lv_obj_t * ui_Schermata_Diagnostica_logger;
extern lv_obj_t * ui_Schermata_Diagnostica_Button7;
extern lv_obj_t * ui_Schermata_Diagnostica_contrmot;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Schermata_Diagnostica;
extern lv_obj_t * uic_Schermata_Diagnostica_logger;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

