// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#ifndef _HMI_DECAPSULATOR_UI_H
#define _HMI_DECAPSULATOR_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////

#include "ui_Scheramata_Avvio.h"
#include "ui_Schermata_Principale.h"
#include "ui_Schermata_Diagnostica.h"
#include "ui_password.h"
#include "ui_EASTER_EGG.h"
#include "ui_Logger1.h"
#include "ui_JOGGER.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * glow1_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1415156368);    // assets/ITSMeccatroniconew2-grigio (1).png
LV_IMG_DECLARE(ui_img_foto_sfondo_resized_png);    // assets/foto sfondo_resized.png
LV_IMG_DECLARE(ui_img_1414324677);    // assets/pngegg (1).png
LV_IMG_DECLARE(ui_img_logo_decapsulator_resized_png);    // assets/logo_decapsulator_resized.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
