// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#include "ui.h"
#include "DecapsulatorPRG.hpp" 
#define SEND()(do{xQueueSend(QueueHandlerHMI_CMD, e, 0);}while(0))

void avvio_macchina(lv_event_t * e)
{
	SEND();
}

void Stop_Macchina(lv_event_t * e)
{
	SEND();
}
