// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void avvio_macchina(lv_event_t * e);
void Stop_Macchina(lv_event_t * e);
void verifica_password(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
