// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#include "ui.h"

void avvio_macchina(lv_event_t * e)
{
	// Your code here
}

void Stop_Macchina(lv_event_t * e)
{
	// Your code here
}

void verifica_password(lv_event_t * e)
{
	// Your code here
}
