// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#ifndef UI_JOGGER_H
#define UI_JOGGER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_JOGGER
extern void ui_JOGGER_screen_init(void);
extern void ui_JOGGER_screen_destroy(void);
extern lv_obj_t * ui_JOGGER;
extern lv_obj_t * ui_JOGGER_BotContrMotPunz;
extern lv_obj_t * ui_JOGGER_ContrMotPunz;
extern lv_obj_t * ui_JOGGER_BotControMotTamb;
extern lv_obj_t * ui_JOGGER_ContrMotTamb;
extern void ui_event_JOGGER_Button3(lv_event_t * e);
extern lv_obj_t * ui_JOGGER_Button3;
extern lv_obj_t * ui_JOGGER_Label7;
extern lv_obj_t * ui_JOGGER_ContrPunz;
extern lv_obj_t * ui_JOGGER_ContrPunz1;
extern lv_obj_t * ui_JOGGER_CLOSE;
extern lv_obj_t * ui_JOGGER_Label9;
extern lv_obj_t * ui_JOGGER_PulsPunz;
extern lv_obj_t * ui_JOGGER_PulsONPunz;
extern lv_obj_t * ui_JOGGER_ONPunz;
extern lv_obj_t * ui_JOGGER_PulsJogIndPunz;
extern lv_obj_t * ui_JOGGER_IndPunz;
extern lv_obj_t * ui_JOGGER_PulsJogAvPunz;
extern lv_obj_t * ui_JOGGER_AvPunz;
extern lv_obj_t * ui_JOGGER_Panel3;
extern lv_obj_t * ui_JOGGER_Panel4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_JOGGER;
extern lv_obj_t * uic_JOGGER_BotContrMotPunz;
extern lv_obj_t * uic_JOGGER_BotControMotTamb;
extern lv_obj_t * uic_JOGGER_ContrMotTamb;
extern lv_obj_t * uic_JOGGER_ContrPunz;
extern lv_obj_t * uic_JOGGER_CLOSE;
extern lv_obj_t * uic_JOGGER_PulsONPunz;
extern lv_obj_t * uic_JOGGER_ONPunz;
extern lv_obj_t * uic_JOGGER_PulsJogIndPunz;
extern lv_obj_t * uic_JOGGER_IndPunz;
extern lv_obj_t * uic_JOGGER_PulsJogAvPunz;
extern lv_obj_t * uic_JOGGER_AvPunz;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

