// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#include "ui.h"

lv_obj_t * uic_JOGGER_AvPunz;
lv_obj_t * uic_JOGGER_PulsJogAvPunz;
lv_obj_t * uic_JOGGER_IndPunz;
lv_obj_t * uic_JOGGER_PulsJogIndPunz;
lv_obj_t * uic_JOGGER_ONPunz;
lv_obj_t * uic_JOGGER_PulsONPunz;
lv_obj_t * uic_JOGGER_CLOSE;
lv_obj_t * uic_JOGGER_ContrPunz;
lv_obj_t * uic_JOGGER_ContrMotTamb;
lv_obj_t * uic_JOGGER_BotControMotTamb;
lv_obj_t * uic_JOGGER_BotContrMotPunz;
lv_obj_t * uic_JOGGER;
lv_obj_t * ui_JOGGER = NULL;
lv_obj_t * ui_JOGGER_BotContrMotPunz = NULL;
lv_obj_t * ui_JOGGER_ContrMotPunz = NULL;
lv_obj_t * ui_JOGGER_BotControMotTamb = NULL;
lv_obj_t * ui_JOGGER_ContrMotTamb = NULL;
lv_obj_t * ui_JOGGER_Button3 = NULL;
lv_obj_t * ui_JOGGER_Label7 = NULL;
lv_obj_t * ui_JOGGER_ContrPunz = NULL;
lv_obj_t * ui_JOGGER_ContrPunz1 = NULL;
lv_obj_t * ui_JOGGER_CLOSE = NULL;
lv_obj_t * ui_JOGGER_Label9 = NULL;
lv_obj_t * ui_JOGGER_PulsPunz = NULL;
lv_obj_t * ui_JOGGER_PulsONPunz = NULL;
lv_obj_t * ui_JOGGER_ONPunz = NULL;
lv_obj_t * ui_JOGGER_PulsJogIndPunz = NULL;
lv_obj_t * ui_JOGGER_IndPunz = NULL;
lv_obj_t * ui_JOGGER_PulsJogAvPunz = NULL;
lv_obj_t * ui_JOGGER_AvPunz = NULL;
lv_obj_t * ui_JOGGER_Panel3 = NULL;
lv_obj_t * ui_JOGGER_Panel4 = NULL;
// event funtions
void ui_event_JOGGER_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Schermata_Diagnostica, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Schermata_Diagnostica_screen_init);
    }
}

// build funtions

void ui_JOGGER_screen_init(void)
{
    ui_JOGGER = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_JOGGER, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_JOGGER, &ui_img_foto_sfondo_resized_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_JOGGER_BotContrMotPunz = lv_button_create(ui_JOGGER);
    lv_obj_set_width(ui_JOGGER_BotContrMotPunz, 200);
    lv_obj_set_height(ui_JOGGER_BotContrMotPunz, 120);
    lv_obj_set_x(ui_JOGGER_BotContrMotPunz, -110);
    lv_obj_set_y(ui_JOGGER_BotContrMotPunz, 0);
    lv_obj_set_align(ui_JOGGER_BotContrMotPunz, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_JOGGER_BotContrMotPunz, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_JOGGER_BotContrMotPunz, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_JOGGER_ContrMotPunz = lv_label_create(ui_JOGGER_BotContrMotPunz);
    lv_obj_set_width(ui_JOGGER_ContrMotPunz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_JOGGER_ContrMotPunz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_JOGGER_ContrMotPunz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_JOGGER_ContrMotPunz, "MOVIMENTAZIONE \nMOTORE\nPUNZONE");
    lv_obj_set_style_text_align(ui_JOGGER_ContrMotPunz, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_JOGGER_BotControMotTamb = lv_button_create(ui_JOGGER);
    lv_obj_set_width(ui_JOGGER_BotControMotTamb, 200);
    lv_obj_set_height(ui_JOGGER_BotControMotTamb, 120);
    lv_obj_set_x(ui_JOGGER_BotControMotTamb, 115);
    lv_obj_set_y(ui_JOGGER_BotControMotTamb, 0);
    lv_obj_set_align(ui_JOGGER_BotControMotTamb, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_JOGGER_BotControMotTamb, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_JOGGER_BotControMotTamb, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_JOGGER_ContrMotTamb = lv_label_create(ui_JOGGER_BotControMotTamb);
    lv_obj_set_width(ui_JOGGER_ContrMotTamb, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_JOGGER_ContrMotTamb, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_JOGGER_ContrMotTamb, LV_ALIGN_CENTER);
    lv_label_set_text(ui_JOGGER_ContrMotTamb, "MOVIMENTAZIONE\nMOTORE\nTAMBURO");
    lv_obj_set_style_text_align(ui_JOGGER_ContrMotTamb, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_JOGGER_Button3 = lv_button_create(ui_JOGGER);
    lv_obj_set_width(ui_JOGGER_Button3, 100);
    lv_obj_set_height(ui_JOGGER_Button3, 31);
    lv_obj_set_x(ui_JOGGER_Button3, 157);
    lv_obj_set_y(ui_JOGGER_Button3, 101);
    lv_obj_set_align(ui_JOGGER_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_JOGGER_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_JOGGER_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_JOGGER_Button3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_JOGGER_Button3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_JOGGER_Label7 = lv_label_create(ui_JOGGER_Button3);
    lv_obj_set_width(ui_JOGGER_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_JOGGER_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_JOGGER_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_JOGGER_Label7, "RITORNA");
    lv_obj_set_style_text_font(ui_JOGGER_Label7, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_JOGGER_ContrPunz = lv_obj_create(ui_JOGGER);
    lv_obj_set_width(ui_JOGGER_ContrPunz, 440);
    lv_obj_set_height(ui_JOGGER_ContrPunz, 250);
    lv_obj_set_align(ui_JOGGER_ContrPunz, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_JOGGER_ContrPunz, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_JOGGER_ContrPunz1 = lv_label_create(ui_JOGGER_ContrPunz);
    lv_obj_set_width(ui_JOGGER_ContrPunz1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_JOGGER_ContrPunz1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_JOGGER_ContrPunz1, 0);
    lv_obj_set_y(ui_JOGGER_ContrPunz1, -100);
    lv_obj_set_align(ui_JOGGER_ContrPunz1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_JOGGER_ContrPunz1, "Controllo motore Punzone");

    ui_JOGGER_CLOSE = lv_obj_create(ui_JOGGER_ContrPunz);
    lv_obj_set_width(ui_JOGGER_CLOSE, 100);
    lv_obj_set_height(ui_JOGGER_CLOSE, 31);
    lv_obj_set_x(ui_JOGGER_CLOSE, -2);
    lv_obj_set_y(ui_JOGGER_CLOSE, 100);
    lv_obj_set_align(ui_JOGGER_CLOSE, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_JOGGER_CLOSE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_JOGGER_Label9 = lv_label_create(ui_JOGGER_CLOSE);
    lv_obj_set_width(ui_JOGGER_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_JOGGER_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_JOGGER_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_JOGGER_Label9, "X   CHIUDI");

    ui_JOGGER_PulsPunz = lv_obj_create(ui_JOGGER_ContrPunz);
    lv_obj_remove_style_all(ui_JOGGER_PulsPunz);
    lv_obj_set_width(ui_JOGGER_PulsPunz, 345);
    lv_obj_set_height(ui_JOGGER_PulsPunz, 66);
    lv_obj_set_x(ui_JOGGER_PulsPunz, 0);
    lv_obj_set_y(ui_JOGGER_PulsPunz, -50);
    lv_obj_set_align(ui_JOGGER_PulsPunz, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_JOGGER_PulsPunz, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_JOGGER_PulsONPunz = lv_button_create(ui_JOGGER_PulsPunz);
    lv_obj_set_width(ui_JOGGER_PulsONPunz, 116);
    lv_obj_set_height(ui_JOGGER_PulsONPunz, 50);
    lv_obj_set_align(ui_JOGGER_PulsONPunz, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_JOGGER_PulsONPunz, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_JOGGER_PulsONPunz, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_JOGGER_PulsONPunz, lv_color_hex(0x01C413), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_JOGGER_PulsONPunz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_JOGGER_ONPunz = lv_label_create(ui_JOGGER_PulsONPunz);
    lv_obj_set_width(ui_JOGGER_ONPunz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_JOGGER_ONPunz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_JOGGER_ONPunz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_JOGGER_ONPunz, "ABILITATO");

    ui_JOGGER_PulsJogIndPunz = lv_button_create(ui_JOGGER_PulsPunz);
    lv_obj_set_width(ui_JOGGER_PulsJogIndPunz, 100);
    lv_obj_set_height(ui_JOGGER_PulsJogIndPunz, 50);
    lv_obj_set_x(ui_JOGGER_PulsJogIndPunz, -115);
    lv_obj_set_y(ui_JOGGER_PulsJogIndPunz, 0);
    lv_obj_set_align(ui_JOGGER_PulsJogIndPunz, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_JOGGER_PulsJogIndPunz, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_JOGGER_PulsJogIndPunz, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_JOGGER_IndPunz = lv_label_create(ui_JOGGER_PulsJogIndPunz);
    lv_obj_set_width(ui_JOGGER_IndPunz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_JOGGER_IndPunz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_JOGGER_IndPunz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_JOGGER_IndPunz, "jog-");

    ui_JOGGER_PulsJogAvPunz = lv_button_create(ui_JOGGER_PulsPunz);
    lv_obj_set_width(ui_JOGGER_PulsJogAvPunz, 100);
    lv_obj_set_height(ui_JOGGER_PulsJogAvPunz, 50);
    lv_obj_set_x(ui_JOGGER_PulsJogAvPunz, 115);
    lv_obj_set_y(ui_JOGGER_PulsJogAvPunz, 0);
    lv_obj_set_align(ui_JOGGER_PulsJogAvPunz, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_JOGGER_PulsJogAvPunz, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_JOGGER_PulsJogAvPunz, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_JOGGER_AvPunz = lv_label_create(ui_JOGGER_PulsJogAvPunz);
    lv_obj_set_width(ui_JOGGER_AvPunz, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_JOGGER_AvPunz, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_JOGGER_AvPunz, LV_ALIGN_CENTER);
    lv_label_set_text(ui_JOGGER_AvPunz, "Jog+");

    ui_JOGGER_Panel3 = lv_obj_create(ui_JOGGER_ContrPunz);
    lv_obj_set_width(ui_JOGGER_Panel3, 20);
    lv_obj_set_height(ui_JOGGER_Panel3, 20);
    lv_obj_set_x(ui_JOGGER_Panel3, -152);
    lv_obj_set_y(ui_JOGGER_Panel3, 38);
    lv_obj_set_align(ui_JOGGER_Panel3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_JOGGER_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_JOGGER_Panel4 = lv_obj_create(ui_JOGGER_ContrPunz);
    lv_obj_set_width(ui_JOGGER_Panel4, 100);
    lv_obj_set_height(ui_JOGGER_Panel4, 50);
    lv_obj_set_x(ui_JOGGER_Panel4, -52);
    lv_obj_set_y(ui_JOGGER_Panel4, 41);
    lv_obj_set_align(ui_JOGGER_Panel4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_JOGGER_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_JOGGER_Button3, ui_event_JOGGER_Button3, LV_EVENT_ALL, NULL);
    uic_JOGGER = ui_JOGGER;
    uic_JOGGER_BotContrMotPunz = ui_JOGGER_BotContrMotPunz;
    uic_JOGGER_BotControMotTamb = ui_JOGGER_BotControMotTamb;
    uic_JOGGER_ContrMotTamb = ui_JOGGER_ContrMotTamb;
    uic_JOGGER_ContrPunz = ui_JOGGER_ContrPunz;
    uic_JOGGER_CLOSE = ui_JOGGER_CLOSE;
    uic_JOGGER_PulsONPunz = ui_JOGGER_PulsONPunz;
    uic_JOGGER_ONPunz = ui_JOGGER_ONPunz;
    uic_JOGGER_PulsJogIndPunz = ui_JOGGER_PulsJogIndPunz;
    uic_JOGGER_IndPunz = ui_JOGGER_IndPunz;
    uic_JOGGER_PulsJogAvPunz = ui_JOGGER_PulsJogAvPunz;
    uic_JOGGER_AvPunz = ui_JOGGER_AvPunz;

}

void ui_JOGGER_screen_destroy(void)
{
    if(ui_JOGGER) lv_obj_del(ui_JOGGER);

    // NULL screen variables
    uic_JOGGER = NULL;
    ui_JOGGER = NULL;
    uic_JOGGER_BotContrMotPunz = NULL;
    ui_JOGGER_BotContrMotPunz = NULL;
    ui_JOGGER_ContrMotPunz = NULL;
    uic_JOGGER_BotControMotTamb = NULL;
    ui_JOGGER_BotControMotTamb = NULL;
    uic_JOGGER_ContrMotTamb = NULL;
    ui_JOGGER_ContrMotTamb = NULL;
    ui_JOGGER_Button3 = NULL;
    ui_JOGGER_Label7 = NULL;
    uic_JOGGER_ContrPunz = NULL;
    ui_JOGGER_ContrPunz = NULL;
    ui_JOGGER_ContrPunz1 = NULL;
    uic_JOGGER_CLOSE = NULL;
    ui_JOGGER_CLOSE = NULL;
    ui_JOGGER_Label9 = NULL;
    ui_JOGGER_PulsPunz = NULL;
    uic_JOGGER_PulsONPunz = NULL;
    ui_JOGGER_PulsONPunz = NULL;
    uic_JOGGER_ONPunz = NULL;
    ui_JOGGER_ONPunz = NULL;
    uic_JOGGER_PulsJogIndPunz = NULL;
    ui_JOGGER_PulsJogIndPunz = NULL;
    uic_JOGGER_IndPunz = NULL;
    ui_JOGGER_IndPunz = NULL;
    uic_JOGGER_PulsJogAvPunz = NULL;
    ui_JOGGER_PulsJogAvPunz = NULL;
    uic_JOGGER_AvPunz = NULL;
    ui_JOGGER_AvPunz = NULL;
    ui_JOGGER_Panel3 = NULL;
    ui_JOGGER_Panel4 = NULL;

}
