// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#include "ui.h"

lv_obj_t * uic_password_TESTO_PSSW;
lv_obj_t * ui_password = NULL;
lv_obj_t * ui_password_Container2 = NULL;
lv_obj_t * ui_password_TESTO_PSSW = NULL;
lv_obj_t * ui_password_TASTIERA_PSSW = NULL;
lv_obj_t * ui_password_ANNULLA_PSSW = NULL;
lv_obj_t * ui_password_Label12 = NULL;
// event funtions
void ui_event_password_TASTIERA_PSSW(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        verifica_password(e);
    }
}

void ui_event_password_ANNULLA_PSSW(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Schermata_Principale, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Schermata_Principale_screen_init);
    }
}

// build funtions

void ui_password_screen_init(void)
{
    ui_password = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_password, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_password, &ui_img_foto_sfondo_resized_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_password_Container2 = lv_obj_create(ui_password);
    lv_obj_remove_style_all(ui_password_Container2);
    lv_obj_set_width(ui_password_Container2, 470);
    lv_obj_set_height(ui_password_Container2, 308);
    lv_obj_set_x(ui_password_Container2, 0);
    lv_obj_set_y(ui_password_Container2, 1);
    lv_obj_set_align(ui_password_Container2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_password_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_password_TESTO_PSSW = lv_textarea_create(ui_password_Container2);
    lv_obj_set_width(ui_password_TESTO_PSSW, 291);
    lv_obj_set_height(ui_password_TESTO_PSSW, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_password_TESTO_PSSW, 14);
    lv_obj_set_y(ui_password_TESTO_PSSW, 15);
    lv_obj_set_style_text_align(ui_password_TESTO_PSSW, LV_ALIGN_TOP_MID, 0);
    lv_textarea_set_accepted_chars(ui_password_TESTO_PSSW, "123456789");
    lv_textarea_set_placeholder_text(ui_password_TESTO_PSSW, "Inserisci PASSWORD");
    lv_textarea_set_one_line(ui_password_TESTO_PSSW, true);
    lv_textarea_set_password_mode(ui_password_TESTO_PSSW, true);
    lv_obj_set_style_text_font(ui_password_TESTO_PSSW, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_password_TASTIERA_PSSW = lv_keyboard_create(ui_password_Container2);
    lv_keyboard_set_mode(ui_password_TASTIERA_PSSW, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_width(ui_password_TASTIERA_PSSW, 465);
    lv_obj_set_height(ui_password_TASTIERA_PSSW, 223);
    lv_obj_set_x(ui_password_TASTIERA_PSSW, -1);
    lv_obj_set_y(ui_password_TASTIERA_PSSW, 38);
    lv_obj_set_align(ui_password_TASTIERA_PSSW, LV_ALIGN_CENTER);

    lv_obj_set_style_text_font(ui_password_TASTIERA_PSSW, &lv_font_montserrat_20, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_password_ANNULLA_PSSW = lv_button_create(ui_password);
    lv_obj_set_width(ui_password_ANNULLA_PSSW, 113);
    lv_obj_set_height(ui_password_ANNULLA_PSSW, 44);
    lv_obj_set_x(ui_password_ANNULLA_PSSW, 154);
    lv_obj_set_y(ui_password_ANNULLA_PSSW, -116);
    lv_obj_set_align(ui_password_ANNULLA_PSSW, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_password_ANNULLA_PSSW, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_password_ANNULLA_PSSW, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_password_ANNULLA_PSSW, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_password_ANNULLA_PSSW, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_password_Label12 = lv_label_create(ui_password_ANNULLA_PSSW);
    lv_obj_set_width(ui_password_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_password_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_password_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_password_Label12, "ANNULLA");
    lv_obj_set_style_text_font(ui_password_Label12, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_keyboard_set_textarea(ui_password_TASTIERA_PSSW, ui_password_TESTO_PSSW);
    lv_obj_add_event_cb(ui_password_TASTIERA_PSSW, ui_event_password_TASTIERA_PSSW, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_password_ANNULLA_PSSW, ui_event_password_ANNULLA_PSSW, LV_EVENT_ALL, NULL);
    uic_password_TESTO_PSSW = ui_password_TESTO_PSSW;

}

void ui_password_screen_destroy(void)
{
    if(ui_password) lv_obj_del(ui_password);

    // NULL screen variables
    ui_password = NULL;
    ui_password_Container2 = NULL;
    uic_password_TESTO_PSSW = NULL;
    ui_password_TESTO_PSSW = NULL;
    ui_password_TASTIERA_PSSW = NULL;
    ui_password_ANNULLA_PSSW = NULL;
    ui_password_Label12 = NULL;

}
