// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#ifndef UI_PASSWORD_H
#define UI_PASSWORD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_password
extern void ui_password_screen_init(void);
extern void ui_password_screen_destroy(void);
extern lv_obj_t * ui_password;
extern lv_obj_t * ui_password_Container2;
extern lv_obj_t * ui_password_TESTO_PSSW;
extern void ui_event_password_TASTIERA_PSSW(lv_event_t * e);
extern lv_obj_t * ui_password_TASTIERA_PSSW;
extern void ui_event_password_ANNULLA_PSSW(lv_event_t * e);
extern lv_obj_t * ui_password_ANNULLA_PSSW;
extern lv_obj_t * ui_password_Label12;
// CUSTOM VARIABLES
extern lv_obj_t * uic_password_TESTO_PSSW;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

