// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#include "ui.h"

lv_obj_t * uic_Schermata_Diagnostica_logger;
lv_obj_t * uic_Schermata_Diagnostica;
lv_obj_t * ui_Schermata_Diagnostica = NULL;
lv_obj_t * ui_Schermata_Diagnostica_Button6 = NULL;
lv_obj_t * ui_Schermata_Diagnostica_Label13 = NULL;
lv_obj_t * ui_Schermata_Diagnostica_Button1 = NULL;
lv_obj_t * ui_Schermata_Diagnostica_logger = NULL;
lv_obj_t * ui_Schermata_Diagnostica_Button7 = NULL;
lv_obj_t * ui_Schermata_Diagnostica_contrmot = NULL;
// event funtions
void ui_event_Schermata_Diagnostica_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Schermata_Principale, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Schermata_Principale_screen_init);
    }
}

// build funtions

void ui_Schermata_Diagnostica_screen_init(void)
{
    ui_Schermata_Diagnostica = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Schermata_Diagnostica, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Schermata_Diagnostica, &ui_img_foto_sfondo_resized_png,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Schermata_Diagnostica_Button6 = lv_button_create(ui_Schermata_Diagnostica);
    lv_obj_set_width(ui_Schermata_Diagnostica_Button6, 100);
    lv_obj_set_height(ui_Schermata_Diagnostica_Button6, 31);
    lv_obj_set_x(ui_Schermata_Diagnostica_Button6, 159);
    lv_obj_set_y(ui_Schermata_Diagnostica_Button6, 121);
    lv_obj_set_align(ui_Schermata_Diagnostica_Button6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Schermata_Diagnostica_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Schermata_Diagnostica_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Schermata_Diagnostica_Button6, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Schermata_Diagnostica_Button6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Schermata_Diagnostica_Label13 = lv_label_create(ui_Schermata_Diagnostica_Button6);
    lv_obj_set_width(ui_Schermata_Diagnostica_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Schermata_Diagnostica_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Schermata_Diagnostica_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Schermata_Diagnostica_Label13, "RITORNA");
    lv_obj_set_style_text_font(ui_Schermata_Diagnostica_Label13, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Schermata_Diagnostica_Button1 = lv_button_create(ui_Schermata_Diagnostica);
    lv_obj_set_width(ui_Schermata_Diagnostica_Button1, 200);
    lv_obj_set_height(ui_Schermata_Diagnostica_Button1, 120);
    lv_obj_set_x(ui_Schermata_Diagnostica_Button1, -110);
    lv_obj_set_y(ui_Schermata_Diagnostica_Button1, 0);
    lv_obj_set_align(ui_Schermata_Diagnostica_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Schermata_Diagnostica_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Schermata_Diagnostica_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Schermata_Diagnostica_logger = lv_label_create(ui_Schermata_Diagnostica_Button1);
    lv_obj_set_width(ui_Schermata_Diagnostica_logger, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Schermata_Diagnostica_logger, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Schermata_Diagnostica_logger, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Schermata_Diagnostica_logger, "LOGGER");

    ui_Schermata_Diagnostica_Button7 = lv_button_create(ui_Schermata_Diagnostica);
    lv_obj_set_width(ui_Schermata_Diagnostica_Button7, 200);
    lv_obj_set_height(ui_Schermata_Diagnostica_Button7, 120);
    lv_obj_set_x(ui_Schermata_Diagnostica_Button7, 115);
    lv_obj_set_y(ui_Schermata_Diagnostica_Button7, 0);
    lv_obj_set_align(ui_Schermata_Diagnostica_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Schermata_Diagnostica_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Schermata_Diagnostica_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Schermata_Diagnostica_contrmot = lv_label_create(ui_Schermata_Diagnostica_Button7);
    lv_obj_set_width(ui_Schermata_Diagnostica_contrmot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Schermata_Diagnostica_contrmot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Schermata_Diagnostica_contrmot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Schermata_Diagnostica_contrmot, "Controllo\nMotori");
    lv_obj_set_style_text_align(ui_Schermata_Diagnostica_contrmot, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Schermata_Diagnostica_Button6, ui_event_Schermata_Diagnostica_Button6, LV_EVENT_ALL, NULL);
    uic_Schermata_Diagnostica = ui_Schermata_Diagnostica;
    uic_Schermata_Diagnostica_logger = ui_Schermata_Diagnostica_logger;

}

void ui_Schermata_Diagnostica_screen_destroy(void)
{
    if(ui_Schermata_Diagnostica) lv_obj_del(ui_Schermata_Diagnostica);

    // NULL screen variables
    uic_Schermata_Diagnostica = NULL;
    ui_Schermata_Diagnostica = NULL;
    ui_Schermata_Diagnostica_Button6 = NULL;
    ui_Schermata_Diagnostica_Label13 = NULL;
    ui_Schermata_Diagnostica_Button1 = NULL;
    uic_Schermata_Diagnostica_logger = NULL;
    ui_Schermata_Diagnostica_logger = NULL;
    ui_Schermata_Diagnostica_Button7 = NULL;
    ui_Schermata_Diagnostica_contrmot = NULL;

}
