// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#ifndef UI_SCHERMATA_PRINCIPALE_H
#define UI_SCHERMATA_PRINCIPALE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Schermata_Principale
extern void ui_Schermata_Principale_screen_init(void);
extern void ui_Schermata_Principale_screen_destroy(void);
extern lv_obj_t * ui_Schermata_Principale;
extern lv_obj_t * ui_Schermata_Principale_CONTEGGIO_CAPSULE;
extern lv_obj_t * ui_Schermata_Principale_capsule_totali;
extern lv_obj_t * ui_Schermata_Principale_capsule_sessione;
extern lv_obj_t * ui_Schermata_Principale_Cont_Caps_Ses1;
extern lv_obj_t * ui_Schermata_Principale_Cont_Caps_Ses;
extern lv_obj_t * ui_Schermata_Principale_Cont_Caps_Tot1;
extern lv_obj_t * ui_Schermata_Principale_Cont_Caps_Tot;
extern void ui_event_Schermata_Principale_BOTTONE_IMPOSTAZIONI(lv_event_t * e);
extern lv_obj_t * ui_Schermata_Principale_BOTTONE_IMPOSTAZIONI;
extern void ui_event_Schermata_Principale_PULS_START(lv_event_t * e);
extern lv_obj_t * ui_Schermata_Principale_PULS_START;
extern lv_obj_t * ui_Schermata_Principale_START;
extern void ui_event_Schermata_Principale_PULS_STOP(lv_event_t * e);
extern lv_obj_t * ui_Schermata_Principale_PULS_STOP;
extern lv_obj_t * ui_Schermata_Principale_STOP;
extern lv_obj_t * ui_Schermata_Principale_LOGO;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Schermata_Principale;
extern lv_obj_t * uic_Schermata_Principale_CONTEGGIO_CAPSULE;
extern lv_obj_t * uic_Schermata_Principale_capsule_totali;
extern lv_obj_t * uic_Schermata_Principale_capsule_sessione;
extern lv_obj_t * uic_Schermata_Principale_Cont_Caps_Tot;
extern lv_obj_t * uic_Schermata_Principale_STOP;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

