// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#include "ui.h"

lv_obj_t * uic_STOP;
lv_obj_t * uic_ContCapsSes;
lv_obj_t * uic_capsule_sessione;
lv_obj_t * uic_ContCapsTot;
lv_obj_t * uic_capsule_totali;
lv_obj_t * uic_CONTEGGIO_CAPSULE;
lv_obj_t * uic_Schermata_Principale;
lv_obj_t * ui_Schermata_Principale = NULL;
lv_obj_t * ui_CONTEGGIO_CAPSULE = NULL;
lv_obj_t * ui_capsule_totali = NULL;
lv_obj_t * ui_Cont_Caps_Tot = NULL;
lv_obj_t * ui_capsule_sessione = NULL;
lv_obj_t * ui_Cont_Caps_Ses = NULL;
lv_obj_t * ui_BOTTONE_IMPOSTAZIONI = NULL;
lv_obj_t * ui_PULS_START = NULL;
lv_obj_t * ui_START = NULL;
lv_obj_t * ui_PULS_STOP = NULL;
lv_obj_t * ui_STOP = NULL;
lv_obj_t * ui_LOGO = NULL;
// event funtions
void ui_event_BOTTONE_IMPOSTAZIONI(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_password, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_password_screen_init);
    }
}

void ui_event_PULS_START(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PULS_STOP, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_PULS_START, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        avvio_macchina(e);
    }
}

void ui_event_PULS_STOP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PULS_START, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_PULS_STOP, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        Stop_Macchina(e);
    }
}

// build funtions

void ui_Schermata_Principale_screen_init(void)
{
    ui_Schermata_Principale = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Schermata_Principale, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Schermata_Principale, &ui_img_foto_sfondo_resized_png,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CONTEGGIO_CAPSULE = lv_obj_create(ui_Schermata_Principale);
    lv_obj_set_width(ui_CONTEGGIO_CAPSULE, 115);
    lv_obj_set_height(ui_CONTEGGIO_CAPSULE, 176);
    lv_obj_set_x(ui_CONTEGGIO_CAPSULE, 165);
    lv_obj_set_y(ui_CONTEGGIO_CAPSULE, -60);
    lv_obj_set_align(ui_CONTEGGIO_CAPSULE, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_CONTEGGIO_CAPSULE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_capsule_totali = lv_label_create(ui_CONTEGGIO_CAPSULE);
    lv_obj_set_width(ui_capsule_totali, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_capsule_totali, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_capsule_totali, 1);
    lv_obj_set_y(ui_capsule_totali, -22);
    lv_obj_set_align(ui_capsule_totali, LV_ALIGN_CENTER);
    lv_label_set_text(ui_capsule_totali, "capsule \n   totali");

    ui_Cont_Caps_Tot = lv_textarea_create(ui_CONTEGGIO_CAPSULE);
    lv_obj_set_width(ui_Cont_Caps_Tot, 105);
    lv_obj_set_height(ui_Cont_Caps_Tot, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Cont_Caps_Tot, -13);
    lv_obj_set_y(ui_Cont_Caps_Tot, -10);
    lv_obj_set_style_text_align(ui_Cont_Caps_Tot, LV_ALIGN_TOP_MID, 0);
    lv_textarea_set_text(ui_Cont_Caps_Tot, "1");
    lv_textarea_set_placeholder_text(ui_Cont_Caps_Tot, "Placeholder...");
    lv_textarea_set_one_line(ui_Cont_Caps_Tot, true);

    ui_capsule_sessione = lv_label_create(ui_CONTEGGIO_CAPSULE);
    lv_obj_set_width(ui_capsule_sessione, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_capsule_sessione, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_capsule_sessione, 2);
    lv_obj_set_y(ui_capsule_sessione, 57);
    lv_obj_set_align(ui_capsule_sessione, LV_ALIGN_CENTER);
    lv_label_set_text(ui_capsule_sessione, "capsule \nsessione");

    ui_Cont_Caps_Ses = lv_textarea_create(ui_CONTEGGIO_CAPSULE);
    lv_obj_set_width(ui_Cont_Caps_Ses, 105);
    lv_obj_set_height(ui_Cont_Caps_Ses, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Cont_Caps_Ses, -13);
    lv_obj_set_y(ui_Cont_Caps_Ses, 70);
    lv_obj_set_style_text_align(ui_Cont_Caps_Ses, LV_ALIGN_TOP_MID, 0);
    lv_textarea_set_text(ui_Cont_Caps_Ses, "1");
    lv_textarea_set_placeholder_text(ui_Cont_Caps_Ses, "Placeholder...");

    ui_BOTTONE_IMPOSTAZIONI = lv_button_create(ui_Schermata_Principale);
    lv_obj_set_width(ui_BOTTONE_IMPOSTAZIONI, 100);
    lv_obj_set_height(ui_BOTTONE_IMPOSTAZIONI, 88);
    lv_obj_set_x(ui_BOTTONE_IMPOSTAZIONI, 166);
    lv_obj_set_y(ui_BOTTONE_IMPOSTAZIONI, 104);
    lv_obj_set_align(ui_BOTTONE_IMPOSTAZIONI, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BOTTONE_IMPOSTAZIONI, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_BOTTONE_IMPOSTAZIONI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BOTTONE_IMPOSTAZIONI, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BOTTONE_IMPOSTAZIONI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_BOTTONE_IMPOSTAZIONI, &ui_img_1414324677, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PULS_START = lv_button_create(ui_Schermata_Principale);
    lv_obj_set_width(ui_PULS_START, 150);
    lv_obj_set_height(ui_PULS_START, 70);
    lv_obj_set_x(ui_PULS_START, 0);
    lv_obj_set_y(ui_PULS_START, 40);
    lv_obj_set_align(ui_PULS_START, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PULS_START, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_PULS_START, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_START = lv_label_create(ui_PULS_START);
    lv_obj_set_width(ui_START, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_START, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_START, LV_ALIGN_CENTER);
    lv_label_set_text(ui_START, "START");
    lv_obj_set_style_text_font(ui_START, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PULS_STOP = lv_button_create(ui_Schermata_Principale);
    lv_obj_set_width(ui_PULS_STOP, 150);
    lv_obj_set_height(ui_PULS_STOP, 70);
    lv_obj_set_x(ui_PULS_STOP, 0);
    lv_obj_set_y(ui_PULS_STOP, 40);
    lv_obj_set_align(ui_PULS_STOP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PULS_STOP, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_PULS_STOP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PULS_STOP, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PULS_STOP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_STOP = lv_label_create(ui_PULS_STOP);
    lv_obj_set_width(ui_STOP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_STOP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_STOP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_STOP, "STOP");
    lv_obj_set_style_text_font(ui_STOP, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LOGO = lv_image_create(ui_Schermata_Principale);
    lv_image_set_src(ui_LOGO, &ui_img_logo_decapsulator_resized_png);
    lv_obj_set_width(ui_LOGO, LV_SIZE_CONTENT);   /// 366
    lv_obj_set_height(ui_LOGO, LV_SIZE_CONTENT);    /// 200
    lv_obj_set_x(ui_LOGO, 1);
    lv_obj_set_y(ui_LOGO, -76);
    lv_obj_set_align(ui_LOGO, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LOGO, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_LOGO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BOTTONE_IMPOSTAZIONI, ui_event_BOTTONE_IMPOSTAZIONI, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PULS_START, ui_event_PULS_START, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_PULS_STOP, ui_event_PULS_STOP, LV_EVENT_ALL, NULL);
    uic_Schermata_Principale = ui_Schermata_Principale;
    uic_CONTEGGIO_CAPSULE = ui_CONTEGGIO_CAPSULE;
    uic_capsule_totali = ui_capsule_totali;
    uic_ContCapsTot = ui_Cont_Caps_Tot;
    uic_capsule_sessione = ui_capsule_sessione;
    uic_ContCapsSes = ui_Cont_Caps_Ses;
    uic_STOP = ui_STOP;

}

void ui_Schermata_Principale_screen_destroy(void)
{
    if(ui_Schermata_Principale) lv_obj_del(ui_Schermata_Principale);

    // NULL screen variables
    uic_Schermata_Principale = NULL;
    ui_Schermata_Principale = NULL;
    uic_CONTEGGIO_CAPSULE = NULL;
    ui_CONTEGGIO_CAPSULE = NULL;
    uic_capsule_totali = NULL;
    ui_capsule_totali = NULL;
    uic_ContCapsTot = NULL;
    ui_Cont_Caps_Tot = NULL;
    uic_capsule_sessione = NULL;
    ui_capsule_sessione = NULL;
    uic_ContCapsSes = NULL;
    ui_Cont_Caps_Ses = NULL;
    ui_BOTTONE_IMPOSTAZIONI = NULL;
    ui_PULS_START = NULL;
    ui_START = NULL;
    ui_PULS_STOP = NULL;
    uic_STOP = NULL;
    ui_STOP = NULL;
    ui_LOGO = NULL;

}
