// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: HMI_Decapsulator

#include "ui.h"

lv_obj_t * uic_Schermata_Principale_STOP;
lv_obj_t * uic_Schermata_Principale_Cont_Caps_Tot;
lv_obj_t * uic_Schermata_Principale_capsule_sessione;
lv_obj_t * uic_Schermata_Principale_capsule_totali;
lv_obj_t * uic_Schermata_Principale_CONTEGGIO_CAPSULE;
lv_obj_t * uic_Schermata_Principale;
lv_obj_t * ui_Schermata_Principale = NULL;
lv_obj_t * ui_Schermata_Principale_CONTEGGIO_CAPSULE = NULL;
lv_obj_t * ui_Schermata_Principale_capsule_totali = NULL;
lv_obj_t * ui_Schermata_Principale_capsule_sessione = NULL;
lv_obj_t * ui_Schermata_Principale_Cont_Caps_Ses1 = NULL;
lv_obj_t * ui_Schermata_Principale_Cont_Caps_Ses = NULL;
lv_obj_t * ui_Schermata_Principale_Cont_Caps_Tot1 = NULL;
lv_obj_t * ui_Schermata_Principale_Cont_Caps_Tot = NULL;
lv_obj_t * ui_Schermata_Principale_BOTTONE_IMPOSTAZIONI = NULL;
lv_obj_t * ui_Schermata_Principale_PULS_START = NULL;
lv_obj_t * ui_Schermata_Principale_START = NULL;
lv_obj_t * ui_Schermata_Principale_PULS_STOP = NULL;
lv_obj_t * ui_Schermata_Principale_STOP = NULL;
lv_obj_t * ui_Schermata_Principale_LOGO = NULL;
// event funtions
void ui_event_Schermata_Principale_BOTTONE_IMPOSTAZIONI(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_password, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_password_screen_init);
    }
}

void ui_event_Schermata_Principale_PULS_START(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Schermata_Principale_PULS_STOP, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Schermata_Principale_PULS_START, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        avvio_macchina(e);
    }
}

void ui_event_Schermata_Principale_PULS_STOP(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Schermata_Principale_PULS_START, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_Schermata_Principale_PULS_STOP, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        Stop_Macchina(e);
    }
}

// build funtions

void ui_Schermata_Principale_screen_init(void)
{
    ui_Schermata_Principale = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Schermata_Principale, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_image_src(ui_Schermata_Principale, &ui_img_foto_sfondo_resized_png,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Schermata_Principale_CONTEGGIO_CAPSULE = lv_obj_create(ui_Schermata_Principale);
    lv_obj_set_width(ui_Schermata_Principale_CONTEGGIO_CAPSULE, 115);
    lv_obj_set_height(ui_Schermata_Principale_CONTEGGIO_CAPSULE, 175);
    lv_obj_set_x(ui_Schermata_Principale_CONTEGGIO_CAPSULE, 165);
    lv_obj_set_y(ui_Schermata_Principale_CONTEGGIO_CAPSULE, -60);
    lv_obj_set_align(ui_Schermata_Principale_CONTEGGIO_CAPSULE, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Schermata_Principale_CONTEGGIO_CAPSULE, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Schermata_Principale_capsule_totali = lv_label_create(ui_Schermata_Principale_CONTEGGIO_CAPSULE);
    lv_obj_set_width(ui_Schermata_Principale_capsule_totali, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Schermata_Principale_capsule_totali, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Schermata_Principale_capsule_totali, 1);
    lv_obj_set_y(ui_Schermata_Principale_capsule_totali, -22);
    lv_obj_set_align(ui_Schermata_Principale_capsule_totali, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Schermata_Principale_capsule_totali, "capsule \n   totali");

    ui_Schermata_Principale_capsule_sessione = lv_label_create(ui_Schermata_Principale_CONTEGGIO_CAPSULE);
    lv_obj_set_width(ui_Schermata_Principale_capsule_sessione, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Schermata_Principale_capsule_sessione, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Schermata_Principale_capsule_sessione, 2);
    lv_obj_set_y(ui_Schermata_Principale_capsule_sessione, 67);
    lv_obj_set_align(ui_Schermata_Principale_capsule_sessione, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Schermata_Principale_capsule_sessione, "capsule \nsessione");

    ui_Schermata_Principale_Cont_Caps_Ses1 = lv_obj_create(ui_Schermata_Principale_CONTEGGIO_CAPSULE);
    lv_obj_set_width(ui_Schermata_Principale_Cont_Caps_Ses1, 100);
    lv_obj_set_height(ui_Schermata_Principale_Cont_Caps_Ses1, 45);
    lv_obj_set_x(ui_Schermata_Principale_Cont_Caps_Ses1, 0);
    lv_obj_set_y(ui_Schermata_Principale_Cont_Caps_Ses1, 25);
    lv_obj_set_align(ui_Schermata_Principale_Cont_Caps_Ses1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Schermata_Principale_Cont_Caps_Ses1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Schermata_Principale_Cont_Caps_Ses = lv_label_create(ui_Schermata_Principale_Cont_Caps_Ses1);
    lv_obj_set_width(ui_Schermata_Principale_Cont_Caps_Ses, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Schermata_Principale_Cont_Caps_Ses, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Schermata_Principale_Cont_Caps_Ses, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Schermata_Principale_Cont_Caps_Ses, "1");

    ui_Schermata_Principale_Cont_Caps_Tot1 = lv_obj_create(ui_Schermata_Principale_CONTEGGIO_CAPSULE);
    lv_obj_set_width(ui_Schermata_Principale_Cont_Caps_Tot1, 100);
    lv_obj_set_height(ui_Schermata_Principale_Cont_Caps_Tot1, 45);
    lv_obj_set_x(ui_Schermata_Principale_Cont_Caps_Tot1, 1);
    lv_obj_set_y(ui_Schermata_Principale_Cont_Caps_Tot1, -60);
    lv_obj_set_align(ui_Schermata_Principale_Cont_Caps_Tot1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Schermata_Principale_Cont_Caps_Tot1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Schermata_Principale_Cont_Caps_Tot = lv_label_create(ui_Schermata_Principale_Cont_Caps_Tot1);
    lv_obj_set_width(ui_Schermata_Principale_Cont_Caps_Tot, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Schermata_Principale_Cont_Caps_Tot, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Schermata_Principale_Cont_Caps_Tot, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Schermata_Principale_Cont_Caps_Tot, "1");

    ui_Schermata_Principale_BOTTONE_IMPOSTAZIONI = lv_button_create(ui_Schermata_Principale);
    lv_obj_set_width(ui_Schermata_Principale_BOTTONE_IMPOSTAZIONI, 100);
    lv_obj_set_height(ui_Schermata_Principale_BOTTONE_IMPOSTAZIONI, 88);
    lv_obj_set_x(ui_Schermata_Principale_BOTTONE_IMPOSTAZIONI, 166);
    lv_obj_set_y(ui_Schermata_Principale_BOTTONE_IMPOSTAZIONI, 104);
    lv_obj_set_align(ui_Schermata_Principale_BOTTONE_IMPOSTAZIONI, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Schermata_Principale_BOTTONE_IMPOSTAZIONI, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Schermata_Principale_BOTTONE_IMPOSTAZIONI, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Schermata_Principale_BOTTONE_IMPOSTAZIONI, lv_color_hex(0xFFFFFF),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Schermata_Principale_BOTTONE_IMPOSTAZIONI, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_image_src(ui_Schermata_Principale_BOTTONE_IMPOSTAZIONI, &ui_img_1414324677,
                                  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Schermata_Principale_PULS_START = lv_button_create(ui_Schermata_Principale);
    lv_obj_set_width(ui_Schermata_Principale_PULS_START, 150);
    lv_obj_set_height(ui_Schermata_Principale_PULS_START, 70);
    lv_obj_set_x(ui_Schermata_Principale_PULS_START, 0);
    lv_obj_set_y(ui_Schermata_Principale_PULS_START, 40);
    lv_obj_set_align(ui_Schermata_Principale_PULS_START, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Schermata_Principale_PULS_START, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Schermata_Principale_PULS_START, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Schermata_Principale_START = lv_label_create(ui_Schermata_Principale_PULS_START);
    lv_obj_set_width(ui_Schermata_Principale_START, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Schermata_Principale_START, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Schermata_Principale_START, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Schermata_Principale_START, "START");
    lv_obj_set_style_text_font(ui_Schermata_Principale_START, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Schermata_Principale_PULS_STOP = lv_button_create(ui_Schermata_Principale);
    lv_obj_set_width(ui_Schermata_Principale_PULS_STOP, 150);
    lv_obj_set_height(ui_Schermata_Principale_PULS_STOP, 70);
    lv_obj_set_x(ui_Schermata_Principale_PULS_STOP, 0);
    lv_obj_set_y(ui_Schermata_Principale_PULS_STOP, 40);
    lv_obj_set_align(ui_Schermata_Principale_PULS_STOP, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Schermata_Principale_PULS_STOP, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_remove_flag(ui_Schermata_Principale_PULS_STOP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Schermata_Principale_PULS_STOP, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Schermata_Principale_PULS_STOP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Schermata_Principale_STOP = lv_label_create(ui_Schermata_Principale_PULS_STOP);
    lv_obj_set_width(ui_Schermata_Principale_STOP, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Schermata_Principale_STOP, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Schermata_Principale_STOP, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Schermata_Principale_STOP, "STOP");
    lv_obj_set_style_text_font(ui_Schermata_Principale_STOP, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Schermata_Principale_LOGO = lv_image_create(ui_Schermata_Principale);
    lv_image_set_src(ui_Schermata_Principale_LOGO, &ui_img_logo_decapsulator_resized_png);
    lv_obj_set_width(ui_Schermata_Principale_LOGO, 175);
    lv_obj_set_height(ui_Schermata_Principale_LOGO, 150);
    lv_obj_set_x(ui_Schermata_Principale_LOGO, 1);
    lv_obj_set_y(ui_Schermata_Principale_LOGO, -76);
    lv_obj_set_align(ui_Schermata_Principale_LOGO, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Schermata_Principale_LOGO, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_Schermata_Principale_LOGO, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Schermata_Principale_BOTTONE_IMPOSTAZIONI, ui_event_Schermata_Principale_BOTTONE_IMPOSTAZIONI,
                        LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Schermata_Principale_PULS_START, ui_event_Schermata_Principale_PULS_START, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Schermata_Principale_PULS_STOP, ui_event_Schermata_Principale_PULS_STOP, LV_EVENT_ALL, NULL);
    uic_Schermata_Principale = ui_Schermata_Principale;
    uic_Schermata_Principale_CONTEGGIO_CAPSULE = ui_Schermata_Principale_CONTEGGIO_CAPSULE;
    uic_Schermata_Principale_capsule_totali = ui_Schermata_Principale_capsule_totali;
    uic_Schermata_Principale_capsule_sessione = ui_Schermata_Principale_capsule_sessione;
    uic_Schermata_Principale_Cont_Caps_Tot = ui_Schermata_Principale_Cont_Caps_Tot;
    uic_Schermata_Principale_STOP = ui_Schermata_Principale_STOP;

}

void ui_Schermata_Principale_screen_destroy(void)
{
    if(ui_Schermata_Principale) lv_obj_del(ui_Schermata_Principale);

    // NULL screen variables
    uic_Schermata_Principale = NULL;
    ui_Schermata_Principale = NULL;
    uic_Schermata_Principale_CONTEGGIO_CAPSULE = NULL;
    ui_Schermata_Principale_CONTEGGIO_CAPSULE = NULL;
    uic_Schermata_Principale_capsule_totali = NULL;
    ui_Schermata_Principale_capsule_totali = NULL;
    uic_Schermata_Principale_capsule_sessione = NULL;
    ui_Schermata_Principale_capsule_sessione = NULL;
    ui_Schermata_Principale_Cont_Caps_Ses1 = NULL;
    ui_Schermata_Principale_Cont_Caps_Ses = NULL;
    ui_Schermata_Principale_Cont_Caps_Tot1 = NULL;
    uic_Schermata_Principale_Cont_Caps_Tot = NULL;
    ui_Schermata_Principale_Cont_Caps_Tot = NULL;
    ui_Schermata_Principale_BOTTONE_IMPOSTAZIONI = NULL;
    ui_Schermata_Principale_PULS_START = NULL;
    ui_Schermata_Principale_START = NULL;
    ui_Schermata_Principale_PULS_STOP = NULL;
    uic_Schermata_Principale_STOP = NULL;
    ui_Schermata_Principale_STOP = NULL;
    ui_Schermata_Principale_LOGO = NULL;

}
