; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc1-n16r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
board = esp32-s3-devkitc1-n16r8
;monitor_raw = yes
monitor_speed = 115200
monitor_filters = esp32_exception_decoder ;Così da vedere direttamente lo stack decodificato se c'è un errore

; Debugger setup link: https://community.platformio.org/t/how-to-use-jtag-built-in-debugger-of-the-esp32-s3-in-platformio/36042
debug_tool = esp-builtin
;debug_init_break = thb setup ; Cambiare questo con il nome della funzione da cui deve partire il debugger
build_type = debug
;Usa "modified" invece di "always" per evitare reload non necessari del codice
debug_load_mode = modified

lib_deps =
			cyijun/ESP32MQTTClient
			madhephaestus/ESP32Servo
			bodmer/TFT_eSPI@^2.5.43
			lvgl/lvgl@^9.3.0

build_flags =   
				-mfix-esp32-psram-cache-issue
				-std=c++2a
				-DBOARD_HAS_PSRAM						;NECESSARIO PER IL FUNZIONAMENTO SU ESP32S3
				-mfix-esp32-psram-cache-issue			;NECESSARIO PER IL FUNZIONAMENTO SU ESP32S3
				
				
				
				;###############################################################
				; TFT_eSPI library setting here (no need to edit library files):
				;###############################################################
				-D USER_SETUP_LOADED=1
				-D RPI_DISPLAY_TYPE=1				    ; NECESSARIO PER IL FUNZIONAMENTO SU ESP32S3
				-D ILI9486_DRIVER=1					    ; DRIVER ILI9486
				-D USE_HSPI_PORT=1					    ; NECESSARIO PER IL FUNZIONAMENTO SU ESP32S3
				-D TOUCH_CS=4							; PIN CHIP SELECT TOUCH
				-D SD_CS=5							    ; PIN CHIP SELECT SD
				-D TFT_DC=6 							; PIN DATA COMMAND
				-D TFT_CS=7 							; PIN CHIP SELECT DISPLAY
				-D TFT_MISO=16							; PIN MISO
				-D TFT_MOSI=15							; PIN MOSI
				-D TFT_SCLK=17							; PIN SCLOCK
				-D TFT_RST=-1  							; Set TFT_RST to -1 if display RESET is connected to ESP32 board RST
				-D LOAD_GLCD=1							; Font 1. Original Adafruit 8 pixel font needs ~1820 bytes in FLASH
				-D LOAD_FONT2=1							; Font 2. Small 16 pixel high font, needs ~3534 bytes in FLASH, 96 characters
				-D LOAD_FONT4=1							; Font 4. Medium 26 pixel high font, needs ~5848 bytes in FLASH, 96 characters
				-D LOAD_FONT6=1							; Font 6. Large 48 pixel font, needs ~2666 bytes in FLASH, only characters 1234567890:-.apm
				-D LOAD_FONT7=1							; Font 7. 7 segment 48 pixel font, needs ~2438 bytes in FLASH, only characters 1234567890:.
				-D LOAD_FONT8=1							; Font 8. Large 75 pixel font needs ~3256 bytes in FLASH, only characters 1234567890:-.
				-D LOAD_GFXFF=1							; FreeFonts. Include access to the 48 Adafruit_GFX free fonts FF1 to FF48 and custom fonts
				-D SMOOTH_FONT=1						;
				-D SPI_FREQUENCY=25000000				; FREQUENZA MASSIMA DISPLAY (MASSIMO 26.6MHz)
				-D SPI_READ_FREQUENCY=25000000			;
				-D SPI_TOUCH_FREQUENCY=10000000			; FREQUENZA MASSIMA TOUCH	(MASSIMO 11MHz)