/** 
 * This file was generated by SquareLine Studio
 * SquareLine Studio version: SquareLine Studio 1.6.0
 * LVGL version: 9.3
 * Project name: HMI_Decapsulator
 * @link Documentazione Squareline: https://docs.squareline.io/docs/
 * @brief Questo file gestisce delle callback associate agli eventi dell'HMI.
 * @attention 	- Evitare operazioni bloccanti all'interno delle callback.
 *				- Seguire la documentazione Doxygen Standard
 *				  @link https://www.doxygen.nl/manual/docblocks.html
 * @author Alessio Pisan
 */

#include "ui.h"
#include "Debug.hpp"
#include "JogMotoriPRG.hpp"
#include "DecapsulatorPRG.hpp"
#include "WiFi_Config.hpp"

/**
 * @example Così andranno fatte praticamente tutte le funzioni degli eventi
 * 
 * @exception Quando farai gli eventi del Jog dovrai anche mandare JogStatus
 * 
 * @exception Quando farai gli eventi del pulsante che fa passare dalla schermata
 *			  Principale a quella di Jog dovrai fare anche :
 *			  @code
 *			  ... 
 *			  vTaskSuspend(MainPrgHandler);
 *			  vTaskResume(JogMotoriPrgHandler);
 *			  ... 
 *			  @endcode

 * @exception Quando farai gli eventi del pulsante che fa passare dalla schermata
 *			  di Jog a quella Principale dovrai fare anche :
 *			  @code
 *			  ... 
 *			  vTaskSuspend(JogMotoriPrgHandler);
 *			  vTaskResume(MainPrgHandler);
 *			  ... 
 *			  @endcode  
 */
void avvio_macchina(lv_event_t * e)
{
	/*CommandQueueHMI_t cmd = defaultCommandQueueHMI;

	cmd.obj  = lv_event_get_original_target(e);
	cmd.evt_type = lv_event_get_code(e);

	sendUpdateHMI(cmd, bool* sendChanges);*/
	LogInfo("START HMI", "PRESSED");
}

void Stop_Macchina(lv_event_t * e)
{
	LogError("STOP HMI", "PRESSED");
}

void verifica_password(lv_event_t * e)
{
    lv_textarea_set_placeholder_text(ui_password_TESTO_PSSW, "Inserisci PASSWORD");

    // Ottieni il testo inserito nella Text Area della password
    const char * password_inserita = lv_textarea_get_text(ui_password_TESTO_PSSW);

    const bool correctPassword = strcmp(password_inserita, PASSWORD_DECAPSULATOR_MANUTENCTOR) == 0;

    // Compara le due stringhe, se sono OK allora è possibile 
    if(correctPassword == true)
    {
        lv_textarea_set_placeholder_text(ui_password_TESTO_PSSW, "Inserisci PASSWORD");
        _ui_screen_change(&ui_Schermata_Diagnostica, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Schermata_Diagnostica_screen_init);
    }
    else
        lv_textarea_set_placeholder_text(ui_password_TESTO_PSSW, "Password Errata");
        
    lv_textarea_set_text(ui_password_TESTO_PSSW, ""); // Reset password
}
